export { Header } from './Header/Header.tsx'
export { Search } from './Search/Search.tsx'
export { Footer } from './Footer/Footer.tsx'
export { Card } from './Card/Card.tsx'
export { Movie } from './Movie/Movie.tsx'
